/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as CascoRouteImport } from './routes/casco'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EsteiraRouteImport } from './routes/esteira'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as IntegralRouteImport } from './routes/integral'
import { Route as LoginRouteImport } from './routes/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const CascoRoute = CascoRouteImport.update({
  id: '/casco',
  path: '/casco',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EsteiraRoute = EsteiraRouteImport.update({
  id: '/esteira',
  path: '/esteira',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegralRoute = IntegralRouteImport.update({
  id: '/integral',
  path: '/integral',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/casco': typeof CascoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/esteira': typeof EsteiraRoute
  '/importar': typeof ImportarRoute
  '/integral': typeof IntegralRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/casco': typeof CascoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/esteira': typeof EsteiraRoute
  '/importar': typeof ImportarRoute
  '/integral': typeof IntegralRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/casco': typeof CascoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/esteira': typeof EsteiraRoute
  '/importar': typeof ImportarRoute
  '/integral': typeof IntegralRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/casco'
    | '/configuracoes'
    | '/esteira'
    | '/importar'
    | '/integral'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/casco'
    | '/configuracoes'
    | '/esteira'
    | '/importar'
    | '/integral'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/casco'
    | '/configuracoes'
    | '/esteira'
    | '/importar'
    | '/integral'
    | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  CascoRoute: typeof CascoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EsteiraRoute: typeof EsteiraRoute
  ImportarRoute: typeof ImportarRoute
  IntegralRoute: typeof IntegralRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casco': {
      id: '/casco'
      path: '/casco'
      fullPath: '/casco'
      preLoaderRoute: typeof CascoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esteira': {
      id: '/esteira'
      path: '/esteira'
      fullPath: '/esteira'
      preLoaderRoute: typeof EsteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integral': {
      id: '/integral'
      path: '/integral'
      fullPath: '/integral'
      preLoaderRoute: typeof IntegralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  CascoRoute: CascoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EsteiraRoute: EsteiraRoute,
  ImportarRoute: ImportarRoute,
  IntegralRoute: IntegralRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
